- .github/workflows/pr-prerelease.yml
> example pr to test pr-prelease workflow

- app/build.gradle
> feat: adds timer trait

- .github/workflows/artifacts-cleanup.yml
> feat: another test

- app/build.gradle
> feat: remove comment

- .github/workflows/github-release.yml
- app/build.gradle
> feat: Final branch

- app/build.gradle
```release-note
example release note
```
> remove test comment

- .github/workflows/github-release.yml
> Test changelog

- app/build.gradle
```release-note
test release note
```
> test pr commit message

- app/build.gradle
```release-note
this is a release note
```
> pr commit message

- app/build.gradle
> test commit

- app/build.gradle
```release-note
a test release note
```
> minor: edit build.gradle

- app/build.gradle
```release-note
this is a release note
```
> minor: pr commit message

- app/build.gradle
```release-note
this is a release note
```
> test grep change

- .github/workflows/github-release.yml
```release-note
updated git action
```
> Branch test

- app/build.gradle
```release-note
example release note
```
> Example merge commit message

- app/src/main/res/values/strings.xml
Changed a string
```release-note
Changed a string
```
> test string change

- .github/workflows/update_changelog.yml
- CHANGELOG.md
```release-note
Add additional action for updating changelog on pr merge
```
> Add additional action for updating changelog on pr merge

- .github/workflows/update_changelog.yml
```release-note
switch to awk instead of sed
```
> switch to awk instead of sed

- app/src/main/res/values/strings.xml
```release-note
string change for testing
```
> string change for testing

- app/src/main/res/values/strings.xml
```release-note
another string change for testing
```
> another string change for testing

- app/src/main/res/values/strings.xml
```release-note
another string change for testing again
```
> another string change for testing again

- .github/workflows/update_changelog.yml
```release-note
fix pr body processing
```
> fix pr body processing

- .github/workflows/update_changelog.yml
```release-note
merge steps
```
> merge steps

- .github/workflows/update_changelog.yml
```release-note
additional pr body debugging
```
> additional pr body debugging

- .github/workflows/update_changelog.yml
```release-note
even more pr body debugging
```
> even more pr body debugging

- .github/workflows/update_changelog.yml
```release-note
pr body extraction tweak
```
> pr body extraction tweak

- .github/workflows/update_changelog.yml
```release-note
pr body extraction remove carraige returns
```
> pr body extraction remove carraige returns

- .github/workflows/update_changelog.yml
```release-note
still debugging extraction
```
> still debugging extraction

- .github/workflows/update_changelog.yml
```release-note
fix pr number and release note location
```
> fix pr number and release note location

- app/src/main/res/values/strings.xml
```release-note
second string change
```
> second string change

- app/src/main/res/values/strings.xml
```release-note
third change/bugfix
```
> third change

- app/src/main/res/values/strings.xml
```release-note
fourth test string change
```
> fourth test string change

- .github/workflows/update_changelog.yml
```release-note
adjust change type extraction
```
> adjust change type extraction

- app/src/main/res/values/strings.xml
```release-note
fifth test feature
```
> fifth test feature

- .github/workflows/github-release.yml
```release-note
use new changelog in git releases
```
> use new changelog in git releases

- CHANGELOG.md
```release-note
Fix format of existing changelog items
```
> Example branch

- .github/workflows/github-release.yml
- .github/workflows/update_changelog.yml
```release-note
update link format in actions
```
> update link format in actions

- .github/workflows/update_changelog.yml
```release-note
avoid delimiter conflict
```
> avoid delimiter conflict

- .github/workflows/update_changelog.yml
```release-note
fix sed syntax
```
> fix sed syntax

- .github/workflows/github-release.yml
```release-note
change release action to auto-run weekly rather than daily
```
> change release action to auto-run weekly rather than daily

- CHANGELOG.md
- app/src/main/res/values/strings.xml
```release-note
include link in all changelog PR refs
```
> include link in all changelog PR refs

- .github/workflows/github-release.yml
- CHANGELOG.md
```release-note
fix unreleased section spacing
```
> fix unreleased section spacing

- CHANGELOG.md
> Major: Update CHANGELOG.md

- app/src/main/java/com/fieldbook/tracker/activities/CollectActivity.java
> major: Update CollectActivity.java

- app/src/main/res/values/strings.xml
_Should this code trigger a major or minor release? Skip if the answer is no, otherwise put an `x` in the box that applies._
```release-note
changed git action major/minor relese trigger
```
> test minor version release

- .github/workflows/update_changelog.yml
- app/src/main/res/values/strings.xml
_Should this code trigger a major or minor release? Skip if the answer is no, otherwise put an `x` in the box that applies._
```release-note
fixed checkbox value retrieval
```
> Example branch test major release 

- app/src/main/res/values/strings.xml
> test major release

- app/src/main/res/values/strings.xml
```release-note
this is a change release note
```
> sample app change again

- app/src/main/res/values/strings.xml
```release-note
this is a fix release note
```
> anohter sample app change again

- app/src/main/res/values/strings.xml
```release-note
test change to trigger minor release
```
> test app change

- app/src/main/res/values/strings.xml
```release-note
another change release note patch test
```
> app change

- app/src/main/res/values/strings.xml
this is a test description
```release-note
this ia a bugfix release note
```
___
> New branch

- app/src/main/res/values/strings.xml
here's a description
```release-note
somethings changed in the app
```
___
> another app change

- .github/workflows/github-release.yml
sdafsdf
```release-note
handle special character errors
```
___
> handle special character errors

- .github/workflows/github-release.yml
```release-note
handle tags outside of sed
```
___
> handle tags outside of sed

- .github/workflows/github-release.yml
sdf
```release-note
more troubleshooting
```
___
> more troubleshooting

- .github/workflows/github-release.yml
dfg
```release-note
more debugging
```
___
> more debugging

- .github/workflows/github-release.yml
```release-note
explicit fetch
```
___
> prevent outdated changelog version with explicit fetch

- .github/workflows/github-release.yml
```release-note
fix indentation
```
___
> fix indentation

- .github/workflows/github-release.yml
```release-note
test different processing
```
___
> test different processing

- .github/workflows/github-release.yml
- CHANGELOG.md
```release-note
fix release block formatting
```
___
> fix release block formatting

- app/src/main/res/values/strings.xml
sdfsd
```release-note
this is a change release note
```
___
> test change

- app/src/main/res/values/strings.xml
sdfsdf
```release-note
a fix release note
```
___
> another test change

- app/src/main/res/values/strings.xml
sdfsadf
```release-note
this is another fix release note
```
___
> yet another test change

- app/src/main/res/values/strings.xml
rtewtewrt
```release-note
test change 5
```
___
> test change 5
